export enum Permission {
  // Work permissions
  WORK_VIEW = 'WORK_VIEW',
  WORK_ASSIGN_SELF = 'WORK_ASSIGN_SELF',
  WORK_ASSIGN_ADMIN = 'WORK_ASSIGN_ADMIN',
  WORK_ASSIGN_DEVELOPER = 'WORK_ASSIGN_DEVELOPER',
  WORK_UPDATE = 'WORK_UPDATE',
  WORK_DOCUMENT = 'WORK_DOCUMENT',
  WORK_REVIEW = 'WORK_REVIEW',

  // Testing permissions
  TEST_VIEW = 'TEST_VIEW',
  TEST_ASSIGN = 'TEST_ASSIGN',
  TEST_EXECUTE = 'TEST_EXECUTE',
  TEST_SUBMIT = 'TEST_SUBMIT',
  TEST_REVIEW = 'TEST_REVIEW',
  TEST_APPROVE = 'TEST_APPROVE',
  TEST_RETEST = 'TEST_RETEST',

  // Device permissions
  DEVICE_VIEW = 'DEVICE_VIEW',
  DEVICE_CREATE = 'DEVICE_CREATE',
  DEVICE_UPDATE = 'DEVICE_UPDATE',
  DEVICE_DEACTIVATE = 'DEVICE_DEACTIVATE',

  // PostgreSQL RDS permissions
  RDS_VIEW = 'RDS_VIEW',
  RDS_MANAGE = 'RDS_MANAGE',
  RDS_USERS_MANAGE = 'RDS_USERS_MANAGE',
  RDS_MIGRATIONS = 'RDS_MIGRATIONS',
  RDS_BACKUP = 'RDS_BACKUP',
  RDS_RESTORE = 'RDS_RESTORE',
  RDS_DATA_MANAGE = 'RDS_DATA_MANAGE',

  // Export permissions
  EXPORT_CREATE = 'EXPORT_CREATE',
  EXPORT_VIEW = 'EXPORT_VIEW',
  EXPORT_DOWNLOAD = 'EXPORT_DOWNLOAD',

  // Audit permissions
  AUDIT_VIEW = 'AUDIT_VIEW',
  AUDIT_VIEW_ALL = 'AUDIT_VIEW_ALL',

  // User and role management permissions
  USER_MANAGE = 'USER_MANAGE',
  ROLE_MANAGE = 'ROLE_MANAGE',
}
